<body>
    <div class="bar"></div>
    <div id="main">
        <div id="toolsmenu">
            <span class="graphic_tool">
                <a href="/showreel.shtml" title="Showreel"><img src="/images/link5.jpg" alt="Showreel" /></a>
            </span>
            <span class="graphic_tool">
                <a href="/info@andriannachristofi.co.uk.pdf" title="CV" target="_blank"><img src="/images/link6.jpg" alt="CV in pdf format opens in new window" /></a>
            </span>
	    <span class="graphic_tool">
                <a href="mailto:info@andriannachristofi.co.uk" title="email info@andriannachristofi.co.uk"><img src="/images/link7.jpg" alt="email info@andriannachristofi.co.uk" /></a>
            </span>
        </div>
