            <div id="hpmenu">
                <span class="graphic_head">
                    <img src="/images/andi_1.jpg" alt="*" />
                    <br />
                    <a href="/presenter.shtml" title="Presenter"><img src="/images/link1.jpg" alt="Presenter" /></a>
                </span>
    
                <span class="graphic_head">
                    <img src="/images/andi_2.jpg" alt="*" />
                    <br />
                    <a href="/singer.shtml" title="Singer"><img src="/images/link2.jpg" alt="Singer" /></a>
                </span>
    
                <span class="graphic_head">
                    <img src="/images/andi_3.jpg" alt="*" />
                    <br />
                    <a href="/actor.shtml" title="Actor"><img src="/images/link3.jpg" alt="Actor" /></a>
                </span>
                <span class="graphic_head">
                    <img src="/images/andi_4.jpg" alt="*" />
                    <br />
                    <a href="/model.shtml" title="Model"><img src="/images/link4.jpg" alt="Model" /></a>
                </span> 
            </div>
