            <div id="hpmenu">
                <span class="graphic_head">
                    <a href="/presenter.shtml" title="Presenter" onMouseOver="rollover(document.images.link1,'on');" onMouseOut="rollover(document.images.link1,'off');"><img src="/images/andi_1.jpg" alt="*" />
                    <br />
                    <img src="/images/link1.jpg" alt="Presenter" id="link1" /></a>
                </span>
    
                <span class="graphic_head">
                    <a onMouseOver="rollover(document.images.link2,'on');" onMouseOut="rollover(document.images.link2,'off');" href="/singer.shtml" title="Singer"><img src="/images/andi_2.jpg" alt="*"/>
                    <br />
                    <img src="/images/link2.jpg" alt="Singer" id="link2" /></a>
                </span>
    
                <span class="graphic_head">
                    <a onMouseOver="rollover(document.images.link3,'on');" onMouseOut="rollover(document.images.link3,'off');" href="/actor.shtml" title="Actor"><img src="/images/andi_3.jpg" alt="*" />
                    <br />
                    <img src="/images/link3.jpg" alt="Actor" id="link3" /></a>
                </span>
                <span class="graphic_head">
                    <a onMouseOver="rollover(document.images.link4,'on');" onMouseOut="rollover(document.images.link4,'off');" href="/model.shtml" title="Model"><img src="/images/andi_4.jpg" alt="*" />
                    <br />
                    <img src="/images/link4.jpg" alt="Model" id="link4" /></a>
                </span> 
            </div>
